<% String title = "Exams"; %>
<%@include file="adminHeader.jsp" %>

<%
    logger.addHandler(fileHandler);
    logger.info("At exams");
    //Get all the neccisary information to fill out page

    List<Term> terms = retriever.getTerms();
    String examList = retriever.getAllExamsInTermString(1158);
    request.setAttribute("examList", examList);
    if (request.getParameter("termId") == null) {
        request.setAttribute("termId", 1158);
        request.setAttribute("termName", "Fall 2015");
    }
%>

<%
    //This code runs to switch info depeding on term
    if (request.getParameterNames() != null && request.getParameter("termId") != null) {
        int term = Integer.parseInt(request.getParameter("termId"));
        examList = retriever.getAllExamsInTermString(term);
        request.setAttribute("examList", examList);
    }
%>
<!-- On load make sure the list of exams is updated-->
<body onload='createList(<%=examList%>)'>


<div class="TermButton">
    <div class="dropdown">
        Term:
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="true">
            <% if (request.getParameter("termName") != null) {
                out.print(request.getParameter("termName"));
            } else {
                out.print("Fall 2015");
            } %>
        </button>
        <ul class="dropdown-menu" id="termDropdown" aria-labelledby="dropdownMenu1">
            <%for(Term term : terms){
            %> <li onclick="submitTerm(<%=term.getId()%>,'<%=term.getTermName()%>')"><%=term.getTermName()%></li>
            <%}
            %>
        </ul>
    </div>
</div>


<div class="generalBorderedContent">

    <!--This is a hidden form that enables term changing -->
    <form NAME="form1">
        <INPUT TYPE="HIDDEN" NAME="termId">
        <INPUT TYPE="HIDDEN" NAME="termName">
    </form>

    <div class="container-fluid">
        <div class="row">

            <div class="col-md-2">
                <div class="list-group" id="examList">
                    <!--Exams go here and are generated by javascript function createList() -->
                </div>
            </div>

            <div class="col-lg-8 examInfo">
                <div id="row">
                    <div class="toprow" id="TestTitle">No Exam Selected</div>
                    <div class="container-fluid">
                        <div class="col-md-5">
                            <!--Left column -->
                            <div class="row" id="refinedRow">
                                <div class="col-md-3" id="">Refined ID::</div>
                                <div class="col-md-4" id="refined"></div>
                            </div>
                            <div class="row" id="typeRow">
                                <div class="col-md-3" id="test">Test Type:</div>
                                <div class="col-md-4" id="examType"></div>
                            </div>
                            <div class="row" id="classRow">
                                <div class="col-md-3" id="classLabel">Class:</div>
                                <div class="col-md-4" id="class"></div>
                            </div>
                            <div class="row" id="sectionRow">
                                <div class="col-md-3" id="sectionLabel">Section:</div>
                                <div class="col-md-4" id="section"></div>
                            </div>

                        </div>
                        <div class="col-md-5">
                            <!--Right column -->
                            <div class="row">
                                <div class="col-md-3" id="statusLavel">Status</div>
                                <div class="col-md-4" id="status"></div>
                            </div>
                            <div class="row">
                                <div class="col-md-3" id="startLabel">Start Date:</div>
                                <div class="col-md-7" id="start"></div>
                            </div>
                            <div class="row">
                                <div class="col-md-3" id="endTimeLabel">End Date:</div>
                                <div class="col-md-7" id="end"></div>
                            </div>
                            <div class="row">
                                <div class="col-md-4" id="examTimeLabel">Exam Duration:</div>
                                <div class="col-md-4" id="examTime"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div><h1 style="text-align: center">Student Appointments</h1></div>

                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Net Id</th>
                            <th>Date</th>
                            <th>Seat</th>
                            <th>Status</th>

                        </tr>
                        </thead>
                        <tbody id="studentAppointments">

                        </tbody>
                    </table>


                    <div class="container">
                        <div class="row" id="utilRow">
                            <div><h1 style="text-align: center">Utilization Before</h1>></div>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Utilization</th>
                                </tr>
                                </thead>
                                <tbody id="utilbefore">

                                </tbody>
                            </table>
                            <div><h1 style="text-align: center">Utilization after</h1>></div>
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Utilization</th>
                                </tr>
                                </thead>
                                <tbody id="utilafter">

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div id="approve" class="row bottomrow">

                </div>
                <div id="deny" class="row bottomrow">

                </div>
            </div>
        </div>
    </div>

    <SCRIPT LANGUAGE="JavaScript">
        <!--
        function switchView(obj, x) {

            $(obj).addClass('active').siblings().removeClass('active');

            var dataToUpdate = JSON.parse(decodeURI(x));

            $("#TestTitle").html(dataToUpdate.examName);
            $("#class").html(dataToUpdate.subject + " " + dataToUpdate.catalogNumber);
            $("#section").html(dataToUpdate.section);
            $("#status").html(dataToUpdate.examStatus);
            $("#start").html(dataToUpdate.startDate);
            $("#end").html(dataToUpdate.endDate);
            $("#examTime").html(dataToUpdate.duration);
            $("#examType").html(dataToUpdate.examType);
            $("#refined").html(dataToUpdate.refinedId);

            $("#studentAppointments").empty();


            if(dataToUpdate.examType =="COURSE"){
                $("#classRow").css('display', 'block');
                $("#sectionRow").css('display', 'block');
            }else{
                $("#classRow").css('display', 'none');
                $("#sectionRow").css('display', 'none');
            }
            if(dataToUpdate.examStatus=="PENDING"){
                $("#utilRow").css("display","block");
                $("#utilbefore").html(dataToUpdate.utilbefore);
                $("#utilafter").html(dataToUpdate.utilafter);
            }else{
                $("#utilRow").css("display","none");
            }




            var buttonToAdd1 = "<input value='Approve Request' class='cancelButton btn-primary' type='button' onclick='javascript:window.open(\x22 approveExam.jsp?ExamRefinedId=" +dataToUpdate.refinedId+" \x22, \x22_self\x22); return;' ></input>";
            var buttonToAdd2 = "<input value='Deny Request' class='cancelButton btn-primary' type='button' onclick='javascript:window.open(\x22 denyExam.jsp?ExamRefinedId=" +dataToUpdate.refinedId+" \x22, \x22_self\x22); return;' ></input>";

            $("#approve").html(buttonToAdd1);
            $("#deny").html(buttonToAdd2);

            for(var i = 0; i<dataToUpdate.appointments.length; i++){

                var trOpen = "<tr>",trclose ="</tr>",thopen="<th>",thclose="</th>";
                var netid = thopen + dataToUpdate.appointments[i].netId + thclose;
                var date = thopen + dataToUpdate.appointments[i].appointmentDate + thclose;
                var status = thopen +  dataToUpdate.appointments[i].appointmentStatus + thclose;
                var seatnum = thopen + dataToUpdate.appointments[i].seatNumber + thclose;
                var tableRowToAppend = trOpen + netid + date + seatnum +status +  trclose;
                $("#studentAppointments").append(tableRowToAppend);
            }

            $("#utilbefore").html(dataToUpdate.utilbefore);
            $("#utilafter").html(dataToUpdate.utilafter);

            $("#utilafter").empty();
            $("#utilbefore").empty();


            for(var i = 0; i<dataToUpdate.utilbefore.length; i++){

                var trOpen = "<tr>",trclose ="</tr>",thopen="<th>",thclose="</th>";

                var date = thopen + dataToUpdate.utilbefore[i].date + thclose;
                var utilization = thopen +  dataToUpdate.utilbefore[i].utilization + thclose;
                var tableRowToAppend = trOpen + date + utilization +  trclose;
                $("#utilbefore").append(tableRowToAppend);
            }
            for(var i = 0; i<dataToUpdate.utilafter.length; i++){

                var trOpen = "<tr>",trclose ="</tr>",thopen="<th>",thclose="</th>";
                var date = thopen + dataToUpdate.utilafter[i].date + thclose;
                var utilization = thopen +  dataToUpdate.utilafter[i].utilization + thclose;
                var tableRowToAppend = trOpen + date + utilization +  trclose;
                $("#utilafter").append(tableRowToAppend);
            }




        }

        function createList(x) {
            console.log("Create List");
            console.log(x);

            for (var i = 0; i < x.length; i++) {
                var examObject = x[i];
                var test = "<a  class='list-group-item' onclick='switchView(this, \x22 " + encodeURI(JSON.stringify(examObject)) + "\x22 ) ' > " + examObject.examName + "</a>";
                $("#examList").append(test);
            }
        }

        function submitTerm(termId, termName) {
            document.form1.termId.value = termId;
            document.form1.termName.value = termName;
            form1.submit();
        }

        function changeTermName(termName) {
            if (termName != "" && termName != null) {
                $("#dropdownMenu1").html(termName);
            }
        }
        // -->
    </SCRIPT>

</div>


</body>
